### ISSUE TITLE
stim300 CRC error

### ISSUE THREAD

**Issue by Leon1128** [vortexntnu/stim300#3]
Hi!
Thanks a lot for your work! 
I try to roslaunch the program with my STIM300. But I get the error：

[ WARN] [1575106728.501836908]: stim300 CRC error

How can i solve it？
Thank you.

**Comment by AndreasVaage** [comment]
Hi Leon,

This is a warning that the Cyclic Redundancy Check is not checking out. Which should indicate that the raw data package read from the sensor is corrupt. There could be several reasons for this: Physical problems like electromagnetic interference, wrong wiring between the sensor and the unit running the driver e.t.c.
Or it could be caused by some bug in the driver, e.g. it is not able to read an entire data-package in one go.
Have you tried running the official software from Sensonor, or accessing the sensor directly using a serial interface as explained in the readme, to verify the sensor and the wiring is working correctly?

**Comment by Leon1128** [comment]
Thank you very much. I found the cause of the error. The default datagram format in the program is RATE_ACC_INCL_TEMP_AUX. But it doesn't match my IMU settings. I modified it in service mode.Then the error was corrected.
